### PR TITLE
make proc_intent() fast again (on big model)

### PR DESCRIPTION
**Pull request by ddorian**
Hi,

I have a `big-model`, which parsing text is 3x slower compared to my `normal model`. With changes inside, it's only 1.5x slower. The normal model should be faster too, just didn't test.

The code isn't as nice as it could be, but if you agree with the changes we can fix it.

Attached is cProfile screenshot, before & after of single `proc_intent()`.

before
after

Makes sense ?

### CODE REVIEW

**Comment by adrienball** [comment]
Hey @ddorian ,
I couldn't manage to reproduce your performance gain, even using a big dataset. I'm a bit concerned about applying changes that make the code slightly more complex if there is not a clear benefit.
Could you describe the structure of your dataset, i.e. number of intents, average number of queries per intent, average number of slots per queries and if you are using builtin entities ?
Cheers
Adrien

**Comment by ddorian** [comment]
@adrienball 
My big model has 10 intents with 1K utterances each. There are no slots or entities defined in the model (the code is still trying to find them), just trying to find intent. Doing a search, I just use the first utterance of the first intent and adding a random word to disable caching.

Even though there's no slot, checking for slot takes the most time (what I try to make faster here). If I manually comment the `find_slot()` part, it gets 6x faster.

How many calls to `initial_strings_from_tokens()` do you get ?
The slowest things were `initial_strings_from_tokens`, which gets rebuild 16K times, and rebuilding tokens from `cache`, and changing the cache-key on parser to be a tuple.

While it looks like a lot of changes, it's mostly:
1. calling `initial_strings_from_tokens` as few as possible
2. don't rebuild `tokens` inside `.compute()`
3. keep `scope` in `tuple` instead of `list` so you could use it as cache key (since list isn't hashable)

Other changes are mostly microoptimizations, since when function gets called 15K times for 1 parse, it adds up.

**Comment by ddorian** [comment]
I will have later a model with slots, so ..

**Comment by adrienball** [comment]
For a single input, the function `initial_string_from_tokens` is called `N = B x T` times where `B` is the number of supported builtin entities in the language (max 7), and `T` is the number of tokens.
If you are seeing 16K calls to the function, that would mean your input is more than 2000 tokens long, is it the case ?

**Comment by ddorian** [comment]
I have 37 tokens. We're working on a fork, and currently rebasing. 
I'll redo the test when we merge with latest and I'll00  reply here again.

**Comment by adrienball** [comment]
Hey @ddorian ,
We've done some significant refactoring and optimizations lately, I'd be interesting to hear about how the latest version works for you.
Cheers

**Comment by ddorian** [comment]
Hi @adrienball 
I'm waiting for a team member to finish a snips merge with our fork and then will test.

**Pull request closed without merging**
